language: rust
os: linux-ppc64le
dist: xenial
sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install libc6

script:
- git clone https://github.com/BurntSushi/ripgrep
- cd ripgrep
- cargo build --release
- ./target/release/rg --version
